version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/tz3
    depends_on:
      - php
      - mysql
  php:
    build:
      context: docekrfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/tz3
  mysql:
    image: "mysql:8.0"
    ports:
      - "3316:3306" #3316 внешний порт
    env_file:
      - mysql/mysql.env
    volumes:
      - tz3_db_data:/var/lib/mysql
  composer:
    build:
      context: docekrfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/tz3
  artisan:
    build:
      context: docekrfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/tz3
    entrypoint: ["php", "/var/www/tz3/artisan"]
volumes:
  tz3_db_data: